### ISSUE TITLE
Python? Django?

### ISSUE THREAD

**Issue by nikopy** [vit1-irk/new-docs#2]
Здравствуйте, Виктор!
Сразу хочу извиниться, что пишу вам в гитхаб в issue.
Я ищу разработчика с опытом в Python (который у вас есть, судя по репозиторию :), хотя бы небольшим опытом в Django, возможностью разговаривать хотя бы на ломаном английском и суммарным опытом программирования от 2 до 100 лет :)
Напишите, пожалуйста, в скайп cv.kulikov@gmail.com (это именно скайп), если это про вас :)
Спасибо

**Comment by vit1-irk** [comment]
Django не пробовал + я студент-первокурсник, и на подработку времени нет. Так что не вариант, извините

P.S. В профиле Гитхаба есть галочка "Available for hire"  специально для потенциальных работодателей. Если отмечена, то тогда писать человеку можно
